// AUTOGENERATED! DO NOT EDIT!
// Generated by "tools/convert_shaders.py"
// Generated from: "/home/mark/Documents/Projects/fejix_runtime/src/fejix_drawer/opengl3/shaders.glsl"

const char *_vertexShader =
   "void main() {"
   "}"
;

