check_include_files("windows.h" FEJIX_HAS_WINAPI)
check_include_files("xcb/xcb.h" FEJIX_HAS_XCB)

if(FEJIX_HAS_WINAPI)
    target_compile_definitions(fejix_runtime PUBLIC "FJ_USE_WINAPI")
elseif(FEJIX_HAS_XCB)
    target_compile_definitions(fejix_runtime PUBLIC "FJ_USE_XCB")
else()
    message(FATAL_ERROR "Platform is not supported")
endif()