#ifndef FEJIX_RUNTIME_EVENTS_H_
#define FEJIX_RUNTIME_EVENTS_H_


#include <stdint.h>


// Events
enum {
    FJ_EVENT_CLOSE = 1,
    FJ_EVENT_RESIZE,
};

struct FjWindow;
struct FjEvent;

typedef uint32_t (*FjEventHandlerFn)(
    struct FjWindow *win,
    struct FjEvent *ev
);


enum {
    /** Every event handler must response with either FJ_OK or FJ_EXIT.
     * FJ_EXIT orders the main loop to break.
     */
    FJ_EXIT = 1
};


struct FjResizeEvent {
    uint32_t width;
    uint32_t height;
};


/**
 * @brief Global Fejix event
 * 
 * @details This structure is passed to FjEventHandler() and holds information
 * about a global GUI event generated by Fejix.
 */
struct FjEvent {
    uint32_t eventType;
    
    union {
        struct FjResizeEvent resizeEvent;
    };
};


#endif // FEJIX_RUNTIME_EVENTS_H_