#ifndef _FEJIX_H_
#define _FEJIX_H_


#include <stdint.h>
#include <math.h>


// Versions
#define FJ_V_MAJOR 0
#define FJ_V_MINOR 0
#define FJ_V_PATCH 1

// Backend identifiers
#define FJ_BK_NONE      0
#define FJ_BK_CAIRO     1
#define FJ_BK_OPENGL3   2

// Helper macros which make life easier
#define FJ_BK_HAS_CAIRO     defined(FJ_BK_USE_CAIRO)
#define FJ_BK_HAS_OPENGL3   defined(FJ_BK_USE_OPENGL3)

// Total number of backends
#define FJ_BK_TOTAL (0      \
    + FJ_BK_HAS_CAIRO       \
    + FJ_BK_HAS_OPENGL3     \
)

#if FJ_BK_TOTAL == 0
#error "[Generated by "fejix.h"] No backend specified!\
 Define FJ_BK_USE_<backend-name> to specify what backend you want to use.\
 Available backend names: CAIRO, OPENGL3."
#endif


struct FjBox {
    float width;
    float height;
};

struct FjWidget {
    struct FjBox boxMin;
    struct FjBox boxMax;

    struct FjWidget *container; // Parent
    struct FjWidget *content[]; // Children
};


#endif // _FEJIX_H_