#ifndef _FEJIX_H_
#define _FEJIX_H_


#include <fejix_runtime/fejix_global.h>


#if FJ_BK_TOTAL == 0
#error "[Generated by "fejix.h"] No backend specified!\
 Define FJ_BK_USE_<backend-name> to specify what backend you want to use.\
 Available backend names: CAIRO, OPENGL3."
#endif


struct FjBox {
    int32_t width;
    int32_t height;
};

struct FjRect {
    int32_t x;
    int32_t y;
    int32_t width;
    int32_t height;
};

struct FjWidget {
    struct FjBox  boxMin;
    struct FjBox  boxMax;
    struct FjRect geometry;

    struct FjWidget *container; // Parent
    struct FjWidget **content;  // Children
    uint32_t contentLength;     // Number of children
};


struct FjColor {
    float r;
    float g;
    float b;
    float a;
};


struct FjRoot {
    struct FjColor background;

    uint32_t backend; // Chosen backend

    struct FjWidget *rootWidget;

#ifdef FJ_WMAPI_SDL
    SDL_Renderer *_sdlRenderer;
    SDL_Texture *_sdlTexture; // Back buffer
#endif

#if FJ_BK_HAS_CAIRO
    cairo_surface_t *_crSurface;
    cairo_t *_crContext;
#endif
};



#ifdef FJ_WMAPI_SDL
    uint32_t fjRootInit_Sdl(
        struct FjRoot *root,
        const uint32_t *parameters,
        SDL_Window *window
    );
#endif
void fjRootDestroy(struct FjRoot *root);
void fjRootSetColor(struct FjRoot *root, float R, float G, float B, float A);

uint32_t fjDraw(struct FjRoot *root);

#endif // _FEJIX_H_