#ifndef FEJIX_RUNTIME_X11_H_
#define FEJIX_RUNTIME_X11_H_


#include <fejix_runtime/definitions.h>
#include <fejix_runtime/events.h>

#ifdef FJ_USE_OPENGL3
#   include <fejix_runtime/internal/platform/x11/opengl.h>
#endif

#include <X11/Xlib-xcb.h>
#include <xcb/sync.h>
#include <xcb/xcb_icccm.h>


struct FjApp {
    struct FjWindow **windows;
    uint32_t windowsLen;

    // Xlib stuff
    Display *xDisplay;
    int32_t xDefaultScreen;

    // Xcb things
    xcb_connection_t *connection;
    xcb_screen_t *screen;
    xcb_atom_t 
        atom_NET_WM_NAME,
        atom_UTF8_STRING,
        atom_WM_PROTOCOLS,
        atom_WM_DELETE_WINDOW,
        atom_NET_WM_SYNC_REQUEST,
        atom_NET_WM_SYNC_REQUEST_COUNTER;

    xcb_visualid_t windowVisualId;
    xcb_colormap_t colormapId;

};


struct FjWindow {
    struct FjApp *app;
    void *data;

    uint32_t width;
    uint32_t height;

    xcb_window_t windowId;

    /// Used for synchronizing window redrawing
    /// See https://fishsoup.net/misc/wm-spec-synchronization.html
    /// Xcb has autogenerated this from an XML specification. Why no docs??
    /// I figured out how to use the counter while reading the Qt 4 code:
    /// https://dreamswork.github.io/qt4/qxcbwindow_8cpp_source.html#l00563
    /// Thanks to Qt devs!
    xcb_sync_counter_t syncCounter;
    xcb_sync_int64_t syncValue;
};



#endif // FEJIX_RUNTIME_X11_H_