#!/usr/bin/python3

# Converts .glsl -> .c

import sys, os
from pathlib import Path

if len(sys.argv) < 3 or sys.argv[1].find('help') != -1:
    print("Usage: python3 convert_shaders.py SOURCE.glsl DESTINATION.c")
    exit(1)


my_path  = os.path.abspath(sys.argv[0])
project_root = Path(my_path).parent.parent
src_path = sys.argv[1]
dst_path = sys.argv[2]

dst_name = str(Path.relative_to(
    Path(os.path.abspath(dst_path)),
    project_root
)).replace('\\', '/')

with open(src_path, 'r') as src_file:
    src = src_file.read()
    src_file.close()

dst = open(dst_path, 'w')

dst.write('// AUTOGENERATED! DO NOT EDIT!\n')
dst.write('// Generated by "tools/convert_shaders.py"\n')
dst.write('// Generated from: "%s"\n\n' % src_path)

for line in src.splitlines():
    line = line.strip().split('//')[0]

    if len(line) == 0:
        continue

    if line.startswith('@begin'):
        varname = line.split('@begin')[1].strip()
        if varname == '':
            print('Syntax: @begin STRINGNAME')
            exit(2)

        dst.write('static const char *%s =\n' % varname)
        continue

    elif line.startswith('@end'):
        dst.write(';\n\n')

    else:
        dst.write('   "%s\\n"\n' % line)

dst.close()
print('Wrote to', dst_name)